### ISSUE TITLE
inconsistencies in flags

### ISSUE THREAD

**Issue by mimoo** [zshipko/ocaml-rust-starter#3]
[The docs](https://github.com/zshipko/ocaml-rs) says you should add some flags to `Cargo.toml` on MacOS:

```toml
[build]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]
```

yet we don't do it here: https://github.com/zshipko/ocaml-rust-starter/blob/master/Cargo.toml

yet (bis) it works fine on my mac without these build flags.

Second, why the C flags here? https://github.com/zshipko/ocaml-rust-starter/blob/master/src/dune#L17

It works fine on my mac without these :o
